### ISSUE TITLE
Onvindbaar bij add-ons

### ISSUE THREAD

**Issue by Xeph20** [dagwieers/plugin.video.regiotv#1]
Beste,

 ik vind hem niet bij de add-ons van kodi

**Comment by piejanssens** [comment]
I confirm  this (Leia).

**Comment by dagwieers** [comment]
Hij is voorgedragen voor de Kodi repository, maar nog niet geaccepteerd.
Zie: https://github.com/xbmc/repo-plugins/pull/2587

Ik heb er geen invloed op wanneer hij wordt gemerged.

**Comment by basrieter** [comment]
Hij is net gemerged (https://github.com/xbmc/repo-plugins/pull/2587)
