### ISSUE TITLE
streams starten niet meer

### ISSUE THREAD

**Issue by mram65** [dagwieers/plugin.video.regiotv#2]
Sinds enkele dagen (of weken?) starten de streams niet meer.
Op verschillende dagen getest met WTV, Focus en een willekeurige andere

**Comment by dagwieers** [comment]
Ik heb gisteren hetzelfde opgemerkt. Het zijn er 3 waar de stream niet meer van werkt, wellicht omdat het adres veranderd is. Als dat geen vast adres is, dan gaan we de website moeten scrapen om de video stream eruit te halen, en dat is complexer, en vatbaar voor fouten als de website verandert.
